import NavBar from '@/components/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import Footer from '@/components/Footer'
import { ClerkProvider } from '@clerk/nextjs'

const nunitoSans = Nunito_Sans({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ['latin-ext']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="es">
        <body className={nunitoSans.className}>
          <NavBar />
          {children}
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  )
}
