import { ClerkProvider } from '@clerk/nextjs'
import type { Metadata } from 'next'
import { nunito } from './lib/fonts'

import Navbar from './components/shared/Navbar/Navbar'
import Footer from './components/shared/footer/Footer'
import { Toaster } from './components/ui/toaster'

import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): React.ReactElement {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={nunito.className}>
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  )
}
