import type { Metadata } from 'next'
import Navbar from '../components/shared/Navbar/Navbar'
import Footer from '../components/shared/footer/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function GeneralLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>): React.ReactElement {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  )
}
